<?php

namespace App;

use App\Entities\Enterprise;
use App\Entities\UserStatus;
use App\Entities\UserType;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Passport\HasApiTokens;

class User extends Authenticatable
{
    use Notifiable, HasApiTokens, SoftDeletes;

    protected $primaryKey = "id";

    protected $table = "users";

    protected $fillable = [
        'name', 'email', 'password','status_id','photo',
        'username','paper_id', 'enterprise_id', 'status_id',
        'last_change_password'
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $casts = [
        'last_change_password' => 'datetime',
        'email_verified_at' => 'datetime',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'deleted_at' => 'datetime'
    ];

    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
    }

    public function type()
    {
        return $this->belongsTo(UserType::class,'paper_id');
    }

    public function status()
    {
        return $this->belongsTo(UserStatus::class,'status_id');
    }

    public function enterprise()
    {
        return $this->belongsTo(Enterprise::class,'enterprise_id');
    }

    public function toArray()
    {
        $data = [
            "id"=>$this->id,
            "name"=>$this->name,
            "email"=>$this->email,
            "username"=>$this->username,
            "type"=>[
                "id"=>$this->type->id,
                "name"=>$this->type->name
            ],
            "status"=>[
                "id"=>$this->status->id,
                "name"=>$this->status->name
            ],
            "enterprise"=>$this->enterprise->toArray(),
            "created_at"=>$this->created_at->format("d/m/Y"),
            "updated_at"=>$this->updated_at->format("d/m/Y")
        ];
        return $data; // TODO: Change the autogenerated stub
    }
}
